services:
    devboard_github.client.factory:
        class: DevBoardLib\GithubApiFacade\Client\KnpLabsClientFactory

    devboard_github.facade.repo.factory:
        class: DevBoardLib\GithubApiFacade\Repo\RepoFacadeFactory
        arguments: ["@devboard_github.client.factory"]

    devboard_github.facade.user.factory:
        class: DevBoardLib\GithubApiFacade\User\UserFacadeFactory
        arguments: ["@devboard_github.client.factory"]
